# W-AI-Land Configuration

# Ollama server configuration
[ollama]
# Base URL for the Ollama server
# Default: http://localhost:11434
host = "http://localhost:11434"

# Model to use for generating responses
# Default: llama2
# Other options: codellama, mistral, llama2:13b, etc.
model = "gpt-oss:120b-cloud"

# Maximum number of tool iterations per query
# Default: 5
max_tool_turns = 5

# Window configuration
[window]
# Initial window dimensions
width = 1200
height = 1200

# Minimum window size
min_width = 400
min_height = 300
